"""The sound module 4.3 shares, and the reason it is synthetic.

Every other module in this atlas measures against a dataset. This one measures
against a *function*: the sound is generated by a source and a filter whose
parameters are written down before the first sample exists, so the pitch at
every instant, the resonances of the filter, and the boundary between one phone
and the next are all exactly known rather than annotated. That turns questions
that are usually qualitative into arithmetic:

  - how much of the pitch survives a mel filterbank (the pitch is known)
  - whether a cepstral coefficient carries the vowel or the voice (both known)
  - how far a forced alignment is from the truth, in milliseconds (the
    boundaries are known)
  - what a window length costs in time resolution and buys in frequency
    resolution (the instantaneous frequency is known in closed form)

A recorded corpus can answer none of those without a human annotator, and a
human annotator cannot mark a boundary to the sample. The cost is that this is
not speech: it is a source-filter caricature of speech, good enough that every
measurement here is about the transform and not about the recording.

Nothing here touches the network or the disk. `python -c "import audio_data"`
and a seed reproduce every sample exactly.
"""
import numpy as np

SR = 8000            # samples per second; enough for the first two formants

# Peterson and Barney's average male formants, in hertz. Five vowels that are
# far apart in the (F1, F2) plane, so a confusion is a real confusion.
VOWELS = {
    "a": (730.0, 1090.0, 2440.0),
    "e": (530.0, 1840.0, 2480.0),
    "i": (270.0, 2290.0, 3010.0),
    "o": (570.0, 840.0, 2410.0),
    "u": (300.0, 870.0, 2240.0),
}
BANDWIDTHS = (60.0, 90.0, 120.0)

# Fricatives are the same filter with a noise source and much higher, broader
# resonances. Written in capitals when they appear in a transcript.
FRICATIVES = {
    "S": (3200.0, 3600.0, 3900.0),
    "F": (1400.0, 2200.0, 3400.0),
    "H": (900.0, 1800.0, 2800.0),
}


def resonator(x, freq, bw, sr=SR):
    """One two-pole resonator, applied in the time domain.

    The pole is at radius exp(-pi*bw/sr) and angle 2*pi*freq/sr, so the
    transfer function of the whole cascade is known in closed form and the
    "true" spectral envelope of any sound made here can be evaluated at any
    frequency without estimating anything.
    """
    from scipy.signal import lfilter

    r = np.exp(-np.pi * bw / sr)
    theta = 2 * np.pi * freq / sr
    a = [1.0, -2 * r * np.cos(theta), r * r]
    gain = 1 - 2 * r * np.cos(theta) + r * r
    # the same difference equation the page runs in JavaScript, one sample at a
    # time; lfilter is only here because a python loop over 8000 samples per
    # second of audio is the difference between a generator that runs in
    # seconds and one that runs in minutes
    return lfilter([gain], a, x)


def envelope_db(freqs, formants, bws=BANDWIDTHS, sr=SR):
    """The exact magnitude response of that cascade, in decibels."""
    w = 2 * np.pi * np.asarray(freqs, dtype=float) / sr
    z = np.exp(1j * w)
    h = np.ones_like(z, dtype=complex)
    for f, bw in zip(formants, bws):
        r = np.exp(-np.pi * bw / sr)
        theta = 2 * np.pi * f / sr
        gain = 1 - 2 * r * np.cos(theta) + r * r
        den = 1 - 2 * r * np.cos(theta) * z ** -1 + (r ** 2) * z ** -2
        h = h * (gain / den)
    return 20 * np.log10(np.abs(h) + 1e-12)


def glottal_source(f0_contour, sr=SR, rng=None, jitter=0.0):
    """A pulse train whose instantaneous frequency is exactly `f0_contour`.

    The phase is accumulated sample by sample, so the pitch is known at every
    instant even while it is changing, which is what makes a pitch tracker
    scoreable here.
    """
    n = len(f0_contour)
    phase = np.cumsum(2 * np.pi * np.asarray(f0_contour, dtype=float) / sr)
    x = np.zeros(n)
    wrapped = np.mod(phase, 2 * np.pi)
    pulses = np.where(np.diff(wrapped) < 0)[0] + 1
    if jitter and rng is not None:
        pulses = np.clip(pulses + rng.integers(-1, 2, len(pulses)), 0, n - 1)
    x[pulses] = 1.0
    # a two sample slope on each pulse, so the spectrum falls off like a real
    # glottal flow rather than being flat to Nyquist
    x = np.convolve(x, np.array([0.5, 1.0, 0.5]), mode="same")
    return x, phase


def vowel(sym, f0_contour, sr=SR, bws=BANDWIDTHS):
    src, _ = glottal_source(f0_contour, sr)
    y = src
    for f, bw in zip(VOWELS[sym], bws):
        y = resonator(y, f, bw, sr)
    return y


def fricative(sym, n, sr=SR, rng=None, bws=(200.0, 250.0, 300.0)):
    """Noise through a filter: the same machinery with a different source."""
    rng = rng or np.random.default_rng(0)
    y = rng.normal(0, 1, n)
    for f, bw in zip(FRICATIVES[sym], bws):
        y = resonator(y, f, bw, sr)
    return y


def chirp(f_start, f_end, seconds, sr=SR):
    """A linear sweep, and its instantaneous frequency at every sample."""
    n = int(seconds * sr)
    t = np.arange(n) / sr
    f_inst = f_start + (f_end - f_start) * t / seconds
    phase = 2 * np.pi * (f_start * t + 0.5 * (f_end - f_start) * t ** 2 / seconds)
    return np.sin(phase), f_inst


def two_tones(f1, f2, seconds, sr=SR):
    n = int(seconds * sr)
    t = np.arange(n) / sr
    return np.sin(2 * np.pi * f1 * t) + np.sin(2 * np.pi * f2 * t)


def utterance(symbols, seed=0, sr=SR, phone_ms=(90, 160), f0_range=(95, 165)):
    """A sequence of phones, with the boundary between each pair recorded.

    Returns the waveform, the list of (symbol, start, end) in samples, and the
    pitch contour, all exact. Consonants are the fricatives; everything else is
    a voiced vowel with a falling pitch, which is what a real declarative
    sentence does.
    """
    rng = np.random.default_rng(seed)
    base = rng.uniform(*f0_range)
    pieces = []
    marks = []
    at = 0
    for i, sym in enumerate(symbols):
        ms = rng.integers(*phone_ms)
        n = int(sr * ms / 1000)
        if sym.isupper():                      # an unvoiced fricative
            piece = fricative(sym, n, sr, rng) * 0.25
        else:
            drift = np.linspace(0, -0.18 * base, n)
            f0 = base + drift + rng.normal(0, 0.6, n).cumsum() * 0.05
            piece = vowel(sym, f0, sr)
            base = float(f0[-1])
        piece = piece / (np.max(np.abs(piece)) + 1e-9)
        # a short taper so the joins do not click, which would be a transient
        # nobody wrote down
        edge = int(0.008 * sr)
        ramp = np.ones(n)
        ramp[:edge] = np.linspace(0, 1, edge)
        ramp[-edge:] = np.linspace(1, 0, edge)
        pieces.append(piece * ramp)
        marks.append((sym, at, at + n))
        at += n
    y = np.concatenate(pieces)
    y = y / (np.max(np.abs(y)) + 1e-9)
    return y, marks


def to_int16(x):
    """What the page gets: sixteen bit samples, so a browser can play them."""
    return np.clip(np.asarray(x) * 32767, -32768, 32767).astype(np.int16)
